### PR TITLE
Locker Hacking

### PR DESCRIPTION
**Pull request by VioletN**
[Changelogs]: #
:cl: Locker Hacking
add: Adds he ability to hack and un-hack lockers using a screwdriver and a multitool.
/:cl:

Re-adds locker hacking. You can now hack lockers by using a screwdriver on them to open the lock panel, and then using a multitool on the opened panel. It takes 10 seconds to hack the closet, and you must stay in place while doing so.

You can also un-hack lockers in order to repair broken locks.

### CODE REVIEW

**Comment by VioletN** [comment]
The Grey Tide just sets "locked" to 0, which doesn't effect whether or not the locker's broken. Secure closets already return ..() if you don't hit them with an ID card, so that works just fine.

**Comment by VioletN** [comment]
I can't figure out how to update this pull request.

**Comment by Profakos** [comment]
Could you make this require wearing gloves with insulation?

**Comment by Profakos** [comment]
@VioletN  I have found it, the proper way is to call electrocute_act.  It checks for gloves if the Safety var is set to 1.  Also for note: Tesla_shock var makes it check your whole suit on top of gloves because it makes the lightning hit you in the chest. This proc doesn't check the powernet. 

Electrocute act doesn't return with any value though so you probably have to check for 0 siemens coeff gloves before calling it.

**Comment by Profakos** [comment]
Mea maxima culpa, turns out human electrocute_act does return with a var due to . = ..(), as I have said on discord, I will fix this for you to make up for your lost time

**Pull request merged**
