### PR TITLE
Moves hissing to ashwalkers

### PR DESCRIPTION
**Pull request by Profakos**
I might make it a preference option instead, like digitgrade legs, what do you think?

### CODE REVIEW

**Comment by VioletN** [comment]
This works fine.

**Comment by AnomalousC** [comment]
It might work fine as a preference option, though I can't imagine anyone actually selecting it.

**Comment by Profakos** [comment]
I would select it :y

**Comment by AnomalousC** [comment]
Good enough! Make it a preference thing then.

**Comment by Profakos** [comment]
I guess if I figure out how the DIGITIGRADE thing works, I can figure out how to swap the tongue.

**Pull request closed without merging**
